config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  devise_for :admins
  get 'home/index'
  root 'home#index'

  get 'admin_dashboard/show'

  devise_for :users
  resources :users
  resources :products
  resources :categories
  resources :orders

  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'

  resources :about_contents, only: [:edit, :update]
  resources :contact_contents, only: [:edit, :update]

  get '/products_page', to: 'products#products_page', as: 'products_page'
  get '/categories_page', to: 'categories#categories_page', as: 'categories_page'

  get '/404', to: 'errors#not_found'

  get '/cart', to: 'carts#show', as: 'cart'
  get '/all_orders', to: 'orders#all_orders', as: 'all_orders'

  post 'add/:id', to: 'carts#add_to_cart', as: 'cart_add'
  patch 'update/:id', to: 'carts#update_quantity', as: 'cart_update'
  get 'remove/:id', to: 'carts#remove_from_cart', as: 'cart_remove'

  resources :orders, only: [:new, :create, :show]

  patch '/orders/:id/update_status', to: 'orders#update_status', as: 'update_order_status'

  resources :taxes, only: [:edit, :update]

  match '*unmatched', to: 'errors#not_found', via: :all
end

app/models/about_content.rb
class AboutContent < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/contact_content.rb
class ContactContent < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items

  # Define the STATUSES constant as a hash
  STATUSES = {
      pending: 'Pending',
      paid: 'Paid',
      shipped: 'Shipped',
      completed: 'Completed',
      cancelled: 'Cancelled'
  }.freeze
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_one_attached :image
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
    def self.province_tax_rates
        {
            "Alberta" => { gst: 0.05, pst: 0, hst: 0 },
            "Ontario" => { gst: 0, pst: 0, hst: 0.13 },
            "Manitoba" => { gst: 0.05, pst: 0.07, hst: 0 },
        }
    end
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = session[:cart] ||= {}
        @products = Product.where(id: @cart.keys)
    end

    def add_to_cart
        product = Product.find(params[:id])
        session[:cart] ||= {}
        session[:cart][product.id.to_s] ||= 0
        session[:cart][product.id.to_s] += 1
        redirect_to cart_path, notice: 'Product added to cart.'
    end

    def remove_from_cart
        session[:cart].delete(params[:id])
        redirect_to cart_path, notice: 'Product removed from cart.'
    end

    def update_quantity
        product_id = params[:id]
        quantity = params[:quantity].to_i
        if quantity > 0
            session[:cart][product_id] = quantity
            notice = 'Quantity updated.'
        else
            session[:cart].delete(product_id)
            notice = 'Product removed from cart.'
        end
        redirect_to cart_path, notice: notice
    end
end

app/controllers/categories_controller.rb
# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
  
    def index
      @categories = Category.all
    end

    def categories_page
      @categories = Category.all
    end
  
    def show
    end
  
    def new
      @category = Category.new
    end
  
    def edit
    end
  
    def create
      @category = Category.new(category_params)
  
      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
  
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      end
    end
  
    private
  
    def set_category
      @category = Category.find(params[:id])
    end
  
    def category_params
      params.require(:category).permit(:name)
    end
end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
# app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @about_content = AboutContent.last.content
  end

  def contact
    @contact_content = ContactContent.last.content
  end
end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
    def edit
        @tax_rate = TaxRate.find(params[:id])  # Assuming you have a model called `TaxRate` to store the rates
    end

    def update
        @tax_rate = TaxRate.find(params[:id])

        if @tax_rate.update(tax_rate_params)
            redirect_to tax_path, notice: 'Tax rate updated successfully.'
        else
            render :edit
        end
    end

    private

    def tax_rate_params
        params.require(:tax_rate).permit(:province, :rate)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/categories_page.html.erb
<!-- app/views/categories/index.html.erb -->
<div class="categories-container">
  <h1>Product Categories</h1>

  <div class="category-list">
    <% @categories.each do |category| %>
      <div class="category-item">
        <h3><%= category.name %></h3>
        <table class="product-table">
          <tbody>
            <% category.products.each do |product| %>
              <tr>
                <td><%= link_to product.name, product_path(product) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<!-- app/views/categories/edit.html.erb -->
<div class="form-container">
  <h1>Edit Category</h1>

  <%= form_with(model: @category, url: category_path(@category), method: :patch) do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field buttons">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Update Category", class: "btn btn-primary" %>
    </div>
  <% end %>
    <div class="buttons">
        <%= link_to 'Back to Categories', categories_path, class: "btn btn-secondary buttons" %>
    </div>
</div>

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->
<div class="categories-container">
  <h1>Product Categories</h1>

  <!-- Button to add new category -->
  <div class="buttons">
    <%= link_to 'New Category', new_category_path, class: "btn btn-primary" %>
  </div>

  <!-- List of categories -->
  <div class="category-list">
    <% @categories.each do |category| %>
      <div class="category-item">
        <h3><%= category.name %></h3>
        <!-- Link to edit category -->
        <%= link_to 'Edit', edit_category_path(category), class: "btn btn-secondary" %>
        <!-- Link to delete category -->
        <%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<!-- app/views/categories/new.html.erb -->
<div class="form-container">
  <h1>New Category</h1>

  <%= form_with(model: @category, url: categories_path, method: :post) do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field buttons">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Create Category", class: "btn btn-primary" %>
    </div>
  <% end %>

 <div class="buttons">
  <%= link_to 'Back to Categories', categories_path, class: "btn btn-secondary" %>
 </div>
</div>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb -->
<div class="form-container">
  <h1><%= @category.name %></h1>

  <!-- Link to edit category -->
  <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-primary" %>

  <!-- Link to delete category -->
  <%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

  <%= link_to 'Back to Categories', categories_path, class: "btn btn-secondary" %>
</div>