config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  devise_for :admins
  get 'home/index'
  root 'home#index'

  get 'admin_dashboard/show'

  devise_for :users
  resources :users
  resources :products
  resources :categories
  resources :orders

  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'

  resources :about_contents, only: [:edit, :update]
  resources :contact_contents, only: [:edit, :update]

  get '/products_page', to: 'products#products_page', as: 'products_page'
  get '/categories_page', to: 'categories#categories_page', as: 'categories_page'

  get '/404', to: 'errors#not_found'

  get '/cart', to: 'carts#show', as: 'cart'
  get '/all_orders', to: 'orders#all_orders', as: 'all_orders'

  post 'add/:id', to: 'carts#add_to_cart', as: 'cart_add'
  patch 'update/:id', to: 'carts#update_quantity', as: 'cart_update'
  get 'remove/:id', to: 'carts#remove_from_cart', as: 'cart_remove'

  resources :orders, only: [:new, :create, :show]

  patch '/orders/:id/update_status', to: 'orders#update_status', as: 'update_order_status'

  resources :taxes, only: [:edit, :update]

  match '*unmatched', to: 'errors#not_found', via: :all
end

app/models/about_content.rb
class AboutContent < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/contact_content.rb
class ContactContent < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items

  # Define the STATUSES constant as a hash
  STATUSES = {
      pending: 'Pending',
      paid: 'Paid',
      shipped: 'Shipped',
      completed: 'Completed',
      cancelled: 'Cancelled'
  }.freeze
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_one_attached :image
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
    def self.province_tax_rates
        {
            "Alberta" => { gst: 0.05, pst: 0, hst: 0 },
            "Ontario" => { gst: 0, pst: 0, hst: 0.13 },
            "Manitoba" => { gst: 0.05, pst: 0.07, hst: 0 },
        }
    end
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = session[:cart] ||= {}
        @products = Product.where(id: @cart.keys)
    end

    def add_to_cart
        product = Product.find(params[:id])
        session[:cart] ||= {}
        session[:cart][product.id.to_s] ||= 0
        session[:cart][product.id.to_s] += 1
        redirect_to cart_path, notice: 'Product added to cart.'
    end

    def remove_from_cart
        session[:cart].delete(params[:id])
        redirect_to cart_path, notice: 'Product removed from cart.'
    end

    def update_quantity
        product_id = params[:id]
        quantity = params[:quantity].to_i
        if quantity > 0
            session[:cart][product_id] = quantity
            notice = 'Quantity updated.'
        else
            session[:cart].delete(product_id)
            notice = 'Product removed from cart.'
        end
        redirect_to cart_path, notice: notice
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
# app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @about_content = AboutContent.last.content
  end

  def contact
    @contact_content = ContactContent.last.content
  end
end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show, :products_page]
    
    def index
        @products = Product.all
    end

    def products_page
        @products = Product.all

        if params[:category].present?
          category = Category.find_by(id: params[:category])
          @products = category.products if category
        end

        @products = @products.where("created_at >= ?", Date.today) if params[:new_products].present?
        @products = @products.where("updated_at >= ?", Date.today) if params[:recently_updated].present?

        @products = @products.paginate(page: params[:page], per_page: 10)
    end

    def show
        @product = Product.find(params[:id])
    end
    
    def new
      @product = Product.new
    end
  
    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render :new
      end
    end
  
    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    end
  
    private
  
    def product_params
        params.require(:product).permit(:name, :description, :price, :stock_quantity, :category_id, :image)
    end
end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
    def edit
        @tax_rate = TaxRate.find(params[:id])  # Assuming you have a model called `TaxRate` to store the rates
    end

    def update
        @tax_rate = TaxRate.find(params[:id])

        if @tax_rate.update(tax_rate_params)
            redirect_to tax_path, notice: 'Tax rate updated successfully.'
        else
            render :edit
        end
    end

    private

    def tax_rate_params
        params.require(:tax_rate).permit(:province, :rate)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<!-- app/views/products/_form.html.erb -->
<div class="form-container">
  <%= form_with(model: product) do |form| %>
    <!-- Form fields for product attributes -->
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.number_field :price %>
    </div>

    <div class="field">
      <%= form.label :stock_quantity %>
      <%= form.number_field :stock_quantity %>
    </div>

    <div class="field">
      <%= form.label :category_id %>
      <%= form.collection_select :category_id, Category.all, :id, :name %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <%= form.submit %>
  <% end %>
</div>

app/views/products/edit.html.erb
<!-- app/views/products/edit.html.erb -->
<h1>Edit Product</h1>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->
<div class="new-admin-container">
  <h1>All Products</h1>
  <div class="buttons">
    <%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>
  </div>
  <table class="product-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Stock Quantity</th>
        <th>Category</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= number_to_currency(product.price) %></td>
          <td><%= product.stock_quantity %></td>
          <td><%= product.category.name %></td>
          <td>
            <%= link_to 'View', product_path(product), class: 'btn btn-secondary' %>
            <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<!-- app/views/products/new.html.erb -->
<h1>New Product</h1>
<%= render 'form', product: @product %>

app/views/products/products_page.html.erb
<!-- app/views/products/index.html.erb -->
<div class="new-container">
  <h1>All Products</h1>

  <%= form_tag products_page_path, method: :get do %>
    <div class="field">
      <%= label_tag 'category', 'Filter by Category:' %>
      <%= select_tag 'category', options_for_select(Category.pluck(:name, :id), params[:category]), include_blank: true %>
    </div>
    
    <div class="field">
      <%= check_box_tag 'new_products', '1', params[:new_products] %>
      <%= label_tag 'new_products', 'New Products' %>
    </div>

    <div class="field">
      <%= check_box_tag 'recently_updated', '1', params[:recently_updated] %>
      <%= label_tag 'recently_updated', 'Recently Updated' %>
    </div>

    <%= submit_tag 'Filter', class: 'btn btn-primary' %>
    <%= link_to 'Clear', products_page_path, class: 'btn btn-secondary' %>
  <% end %>

  <table class="product-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Stock Quantity</th>
        <th>Category</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= number_to_currency(product.price) %></td>
          <td><%= product.stock_quantity %></td>
          <td><%= product.category.name %></td>
          <td>
            <%= link_to 'View', product_path(product), class: 'btn btn-secondary' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @products %>

  <br><br>
</div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->
<div class="product-details">
    <h1><%= @product.name %></h1>
    <p><strong>Description:</strong> <%= @product.description %></p>
    <p><strong>Price:</strong> <%= number_to_currency(@product.price) %></p>
    <p><strong>Stock Quantity:</strong> <%= @product.stock_quantity %></p>
    <p><strong>Category:</strong> <%= @product.category.name %></p>

        <% if @product.image.attached? %>
            <%= image_tag @product.image, class: "product-image" %>
        <% else %>
            <p>No image available</p>
        <% end %>

    <div class="actions">
        <% if current_user.present? && current_user.is_admin %>
            <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-primary" %>
            <%= link_to 'Delete', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <%= link_to 'Back to Products', products_path, class: "btn btn-secondary" %>
            <br><br>
            <%= button_to 'Add to Cart', cart_add_path(@product), method: :post, class: 'btn btn-danger' %>
        <% else %>
            <br>
            <%= button_to 'Add to Cart', cart_add_path(@product), method: :post, class: 'btn btn-danger' %>
            <br>
            <%= link_to 'Back to Products', products_page_path, class: "btn btn-secondary" %>
        <% end %>
    </div>
</div>